services:
  db:
    image: postgres:17
    container_name: lucy_db
    
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"

    volumes:
      - lucy_db_data:/var/lib/postgresql/data

    networks:
      - lucy_rest_network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: lucy_rest_app
    
    ports:
      - "8000:8000"

    environment:
      PRODUCTION: "True"
      PG_HOST: db

    networks:
      - lucy_rest_network

    depends_on:
      db:
        condition: service_healthy

volumes:
  lucy_db_data:

networks:
  lucy_rest_network:
